name: 'Codecov'

on:
  push:
    branches:
      - main

env:
  GO_VERSION: '^1.20.4'

jobs:
  codecov:
    name: 'Codecov'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Setup go ${{ env.GO_VERSION }}'
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: 'Test'
        run: 'go test -race -coverprofile=coverage.out -covermode=atomic ./...'
      - name: 'Upload coverage reports to Codecov'
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}